name: Add feature-request comment
on:
  issues:
    types:
      - labeled

permissions:
  issues: write

jobs:
  add-comment-to-feature-request-issues:
    if: github.event.label.name == 'feature-request'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPO: ${{ github.repository }}
      NUMBER: ${{ github.event.issue.number }}
      BODY: >
        Thank you for your issue! We have categorized this issue as a feature
        request. In doing so, we are not committing to implementing this
        feature. We have however added it to our backlog and will consider it
        for future releases based on community feedback and our own product
        roadmap. 


        Unless you see a help-wanted label, we are not currently looking for
        external contributions to this feature.


        If you come across this issue and would like to see it implemented,
        please add a thumbs up! This will help us prioritize the feature. Please
        only comment if you have additional information or viewpoints to
        contribute.
    steps:
      - run: gh issue comment "$NUMBER" --body "$BODY"
