name: Add unable-to-reproduce comment
on:
  issues:
    types:
      - labeled

permissions:
  issues: write

jobs:
  add-comment-to-unable-to-reproduce-issues:
    if: github.event.label.name == 'unable-to-reproduce'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPO: ${{ github.repository }}
      NUMBER: ${{ github.event.issue.number }}
      LABELS: more-info-needed
      BODY: >
        Thank you for your issue! Unfortunately, we are unable to reproduce the
        issue you are experiencing. Please provide more information so we can
        help you.


        Here are some tips for writing reproduction steps: 
          - Step by step instructions accompanied by screenshots or screencasts
        are the best.
          - Be as specific as possible; Include as much detail as you can. 
          - If not already provided, include the version of the software you are
        using. 
          - If not already provided, include the version of the operating system
        you are using and any environment factors you can think of.
          - If you are using a custom configuration, please provide it.
          - If relevant and can be shared, provide the repository or code you
        are using.
    steps:
      - run: gh issue edit "$NUMBER" --add-label "$LABELS"
      - run: gh issue comment "$NUMBER" --body "$BODY"
